name: Build and Deploy Financeiro API Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-deploy:
    name: Build Financeiro API Docker Image
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Notify Discord (Build Started)
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Docker", "content": "🚀 **Build da imagem Financeiro API iniciado!**\nRepositório: `${{ github.repository }}`\nBranch/Tag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }} || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (branch main)
      if: github.ref == 'refs/heads/main'
      run: |
        docker build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/financeiro-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/financeiro-api:latest

    - name: Build and push Docker image (tagged release)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/financeiro-api:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/financeiro-api:${{ github.ref_name }}

  report-status:
    name: Report Build Status
    needs: build-deploy
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Notify Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Docker", "content": "✅ **Financeiro API Docker Image Build Sucesso!**\nBranch/Tag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Docker", "content": "❌ **Falha ao buildar a imagem do Financeiro API!**\nBranch/Tag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}